# Docker Compose para desenvolvimento local
# Uso: docker-compose -f docker-compose.dev.yml up

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: queimadai-postgres-dev
    environment:
      POSTGRES_DB: queimadai
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d queimadai"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: queimadai-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data

  # API Service (for hybrid development)
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    container_name: queimadai-api-dev
    environment:
      NODE_ENV: development
      PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: queimadai
      DB_USER: postgres
      DB_PASSWORD: postgres123
      REDIS_URL: redis://redis:6379
      LOG_LEVEL: debug
    volumes:
      - ./api/src:/app/src:ro
      - ./api/uploads:/app/uploads
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # pgAdmin (Interface web para PostgreSQL)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: queimadai-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@queimadai.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_dev_data:
  redis_dev_data:
  pgadmin_data:

networks:
  default:
    name: queimadai-dev-network
